# Site settings
title: CodeDancing
header-img: "img/bright.jpg"
tagline: "吉光片羽"  
description: "努力coding"  
baseurl: ""
url: "http://codedancing.com"  
#url: "http://localhost:4000"

# About/contact
owner: 
  name: "Justlearn"
  email: xiaolei_info@163.com
  bio: "明朝即長路 惜取此時心"

# Data
gavatar: http://dreamofbook.qiniudn.com/Az..png
favicon: img/blingeye.jpg


# Build settings  
# use Github Flavored Markdown !important  
# document: http://jekyllrb.com/docs/configuration/#kramdown  
markdown: kramdown
kramdown:
  input: GFM
highlighter: pygments

gems: [jekyll-paginate]
permalink: none
paginate: 9
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone: Asia/Beijing

# Title


# Defaults for posts
defaults:
  -
    scope: 
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Azeril"
      header-img: "img/fantasy.jpg" # We don't want posts without a header image, that whould mean white on white

# Comments 
comments :
  provider : duoshuo
  duoshuo :
    short_name : Justlearn
  disqus :
      short_name : Justlearn

# Analytics and webmaster tools stuff goes here
google_analytics: UA-66863061-1
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Links to include in footer navigation
